### ISSUE TITLE
Support loading files relative to project root directory

### ISSUE THREAD

**Issue by tunniclm** [IBM-Swift/Configuration#12]
Commonly we store configuration files in the project root (or a subdirectory of it like "config").
It is desirable to be able to specify:

```
manager.load(file: "config.json", relativeFrom: .project)
```

Additionally, it would be good to have this continue to work if the executable is not located in `.build/debug` or `.build/release`, for example, in some other part of the project tree. Therefore the project root should be where the `Package.swift` resides.

**Comment by tunniclm** [comment]
I have provided a PR https://github.com/IBM-Swift/Configuration/pull/11 that implement both this and #13

**Comment by tunniclm** [comment]
Ah, the new tests fail on macOS because the executable is the test runner when you are running tests. These tests fail with the old way of getting the executable as well.

I will see if there's a way to fix that, or else I can remove the test. Either way this method of finding the executable is no worse than before in this respect, and better in the ways noted above.

**Comment by youming-lin** [comment]
Closed by PR #16.
