### ISSUE TITLE
Support more robust determination of the executable location

### ISSUE THREAD

**Issue by tunniclm** [IBM-Swift/Configuration#13]
Using `CommandLine.arguments[0]` is problematic for the case where the executable is run via a relative rather than absolute path, or when it is run via `PATH`. This causes problems loading config files in Bluemix.

`Bundle.main.executableURL` and friends offer a more robust solution is my testing. However, it is not yet supported on Linux Foundation. However, 
`URL(fileURLWithPath: "/proc/self/exe").resolvingSymlinksInPath()` provides a fallback for Linux.

**Comment by tunniclm** [comment]
I have provided a PR https://github.com/IBM-Swift/Configuration/pull/11 that implement both this and #12

**Comment by tunniclm** [comment]
The new tests I added fail on macOS because the executable is the test runner when you are running tests. These tests fail with the old way of getting the executable as well.

I will see if there's a way to fix that, or else I can remove the test. Either way this method of finding the executable is no worse than before in this respect, and better in the ways noted above.

**Comment by tunniclm** [comment]
I have added 2 more PRs, based on #11
* #14 - adds a test program that is executed to test loading works outside XCTest runner (to test what happens in a real application, rather than just in tests)
* #15 - adds a modification that makes loading work inside XCTest runner (which fixes the new tests failing on macOS, plus allows exe and project relative config loading to work from tests)

**Comment by tunniclm** [comment]
NOTE: the merge order matters here. For example, If we want all 3 PRs, then the merge order would be:
* #14 (merging test program into the #11 PR)
* #15 (merging XCTest runnner support into #11 PR)
* #11 (merging .project and robustness + test program + XCTest runner support into `master`)

**Comment by youming-lin** [comment]
Closed by PR #16.
