### ISSUE TITLE
Use warning log level when file cannot be loaded.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Configuration#34]
Currently the error log level is used when a file cannot be loaded. Not finding a file is a very common scenario in our apps. It would be better to use, say warning as the log level for logging the message that states that a file cannot be loaded.

**Comment by youming-lin** [comment]
Fixed in #35

**Comment by youming-lin** [comment]
v1.0.1 released: https://github.com/IBM-Swift/Configuration/releases/tag/1.0.1
